#!/usr/bin/env python3
from __future__ import annotations
from .config import baseline, eval_params, severity_map, sort_by_severity
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import argparse
import os

import matplotlib
matplotlib.use("Agg")


ESTIMATORS = ("height_prior", "ground_plane", "fused")
COLOURS = {"height_prior": "#1f77b4",
           "ground_plane": "#d62728", "fused": "#2ca02c"}


def ordered(df):
    order = sort_by_severity(df["condition"].unique().tolist())
    df = df.copy()
    df["condition"] = pd.Categorical(
        df["condition"], categories=order, ordered=True)
    df["severity"] = df["condition"].astype(str).map(severity_map())
    return df.sort_values(["severity", "condition"]), order


def fig_range_error(rng, out):
    rng, order = ordered(rng)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(13, 4.6))
    x = np.arange(len(order))

    for name in ESTIMATORS:
        g = rng[rng["estimator"] == name].set_index("condition").reindex(order)
        a1.plot(x, g["absrel"] * 100, "o-", label=name, color=COLOURS[name])
        a2.plot(x, g["rmse_m"], "o-", label=name, color=COLOURS[name])

    for ax, ylab, title in ((a1, "AbsRel (%)", "Relative range error"),
                            (a2, "RMSE (m)", "Absolute range error")):
        ax.set_xticks(x)
        ax.set_xticklabels(order, rotation=35, ha="right", fontsize=8)
        ax.set_ylabel(ylab)
        ax.set_title(title)
        ax.grid(alpha=0.3)
        ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out, dpi=140)
    plt.close(fig)


def fig_by_distance(rng, out):
    bins = [c for c in rng.columns if c.startswith("rmse_") and c.endswith("m")
            and c != "rmse_m"]
    if not bins:
        return False
    rng, order = ordered(rng)
    base = baseline()
    worst = order[-1]
    show = [c for c in (base, worst) if c in order]

    fig, axes = plt.subplots(1, len(show), figsize=(
        6 * len(show), 4.2), squeeze=False)
    labels = [b.replace("rmse_", "").replace("m", "").replace("_", "-") + " m"
              for b in bins]

    for ax, cond in zip(axes[0], show):
        for name in ESTIMATORS:
            row = rng[(rng["condition"] == cond) & (rng["estimator"] == name)]
            if row.empty:
                continue
            ax.plot(labels, row[bins].values[0], "o-",
                    label=name, color=COLOURS[name])
        ax.set_title(f"{cond}")
        ax.set_ylabel("RMSE (m)")
        ax.grid(alpha=0.3)
        ax.legend(fontsize=8)
    fig.suptitle(
        "Range error by distance: baseline vs worst condition", fontsize=11)
    fig.tight_layout()
    fig.savefig(out, dpi=140)
    plt.close(fig)
    return True


def fig_latency(lsum, out):
    if lsum.empty:
        return False
    lsum, order = ordered(lsum)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(13, 4.6))
    x = np.arange(len(order))
    w = 0.26

    for i, name in enumerate(ESTIMATORS):
        g = lsum[lsum["estimator"] == name].set_index(
            "condition").reindex(order)
        a1.bar(x + (i - 1) * w, g["mean_latency_s"] * 1000, w,
               label=name, color=COLOURS[name])
        a2.bar(x + (i - 1) * w, g["miss_rate"] * 100, w,
               label=name, color=COLOURS[name])

    a1.axhline(0, color="k", lw=0.8)
    a1.set_ylabel("Brake latency (ms)")
    a1.set_title(f"Brake trigger latency (TTC < {eval_params()['ttc_brake_threshold_s']}s)\n"
                 "positive = LATE = unsafe", fontsize=10)
    a2.set_ylabel("Miss rate (%)")
    a2.set_title("Braking events never triggered", fontsize=10)
    for ax in (a1, a2):
        ax.set_xticks(x)
        ax.set_xticklabels(order, rotation=35, ha="right", fontsize=8)
        ax.grid(alpha=0.3, axis="y")
        ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out, dpi=140)
    plt.close(fig)
    return True


def md_table(df, cols, fmt=None):
    fmt = fmt or {}
    head = "| " + " | ".join(cols) + " |"
    sep = "|" + "|".join("---" for _ in cols) + "|"
    lines = [head, sep]
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r.get(c)
            if pd.isna(v):
                cells.append("—")
            elif c in fmt:
                cells.append(fmt[c](v))
            elif isinstance(v, float):
                cells.append(f"{v:.3f}")
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def write_markdown(rng, lsum, path, figs):
    rng, order = ordered(rng)
    def pct(v): return f"{v*100:.1f}%"
    parts = ["# Auto-generated results",
             "",
             "> Generated by `src/report.py`. Numbers only — the interpretation",
             "> belongs in `RESULTS.md`.",
             "", "## Range error", "",
             md_table(rng, ["condition", "estimator", "n", "absrel", "rmse_m",
                            "bias_m", "invalid_frac"],
                      {"absrel": pct, "invalid_frac": pct}),
             ""]

    for f in figs:
        parts += [f"![{f}]({f})", ""]

    if not lsum.empty:
        lsum_o, _ = ordered(lsum)
        parts += ["## Brake latency", "",
                  md_table(lsum_o, ["condition", "estimator", "n_events",
                                    "miss_rate", "mean_latency_s",
                                    "p95_latency_s", "mean_extra_distance_m"],
                           {"miss_rate": pct}),
                  ""]

        hit = lsum_o.dropna(subset=["mean_latency_s"])
        if not hit.empty:
            w = hit.loc[hit["mean_latency_s"].idxmax()]
            parts += ["## Headline", "",
                      f"> Under `{w['condition']}`, the `{w['estimator']}` estimator "
                      f"crosses the {eval_params()['ttc_brake_threshold_s']} s brake "
                      f"threshold **{w['mean_latency_s']*1000:+.0f} ms** "
                      f"{'late' if w['mean_latency_s'] > 0 else 'early'} "
                      f"({w['mean_extra_distance_m']:+.2f} m of travel), and misses "
                      f"the trigger on {w['miss_rate']*100:.1f}% of closing events.",
                      ""]

            # Spread must be measured PER ESTIMATOR across conditions. Pooling
            # all rows mixes two axes: estimators differ from each other by
            # construction, and that difference will mask a total absence of
            # variation across conditions -- which is precisely the thing this
            # check exists to catch.
            spread = hit.groupby("estimator")["mean_latency_s"].agg(
                lambda s: s.max() - s.min()).max()
            worst_lat = hit["mean_latency_s"].max()

            if spread < 0.05 or worst_lat <= 0:
                parts += ["", "## No failure boundary found", "",
                          f"Latency variation across conditions is only "
                          f"{spread*1000:.0f} ms (largest for any single estimator), "
                          f"and the worst-case trigger is {worst_lat*1000:+.0f} ms.",
                          "",
                          "The condition matrix is not severe enough to be informative.",
                          "A benchmark that finds no failure has measured nothing.",
                          "",
                          "Extend it with custom `carla.WeatherParameters`: raise",
                          "`fog_density` toward 100, `precipitation` and",
                          "`precipitation_deposits` toward 100, and drop",
                          "`sun_altitude_angle` below 0. Add rows to",
                          "`configs/conditions.yaml` and re-run from phase 1.", ""]

    with open(path, "w") as f:
        f.write("\n".join(parts))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="./results")
    args = ap.parse_args()
    R = args.results

    rng = pd.read_csv(os.path.join(R, "range_summary.csv"))
    lpath = os.path.join(R, "latency_summary.csv")
    # An empty latency CSV means no braking events occurred, which is a valid
    # outcome, not an error. pandas raises EmptyDataError on a header-only file.
    lsum = pd.DataFrame()
    if os.path.exists(lpath) and os.path.getsize(lpath) > 0:
        try:
            lsum = pd.read_csv(lpath)
        except pd.errors.EmptyDataError:
            pass
    if lsum.empty:
        print("No braking events. TTC never crossed the threshold -- the ego")
        print("keeps a safe gap, so closing speed stays low. Recapture with")
        print("tm.ignore_vehicles_percentage(ego, 100) for genuine closing.")

    figs = []
    fig_range_error(rng, os.path.join(R, "fig1_range_error_vs_severity.png"))
    figs.append("fig1_range_error_vs_severity.png")
    if fig_by_distance(rng, os.path.join(R, "fig2_error_by_distance.png")):
        figs.append("fig2_error_by_distance.png")
    if fig_latency(lsum, os.path.join(R, "fig3_brake_latency.png")):
        figs.append("fig3_brake_latency.png")

    out = os.path.join(R, "RESULTS_AUTO.md")
    write_markdown(rng, lsum, out, figs)
    print(f"Wrote {out} and {len(figs)} figures to {R}")
    print("Now write the argument in results/RESULTS.md. The tables are not the finding.")


if __name__ == "__main__":
    main()
